services:
  whoami:
    container_name: whoami
    hostname: whoami
    image: traefik/whoami:${WHOAMI_VERSION:-latest}
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN:-docker.localhost}`)
      - traefik.http.routers.whoami.service=whoami
      - traefik.http.services.whoami.loadbalancer.server.port=80

networks:
  proxy:
    external: true
