services:
  qbittorrent:
    image: linuxserver/qbittorrent:${QBITTORRENT_VERSION:-latest}
    container_name: qbittorrent
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
    volumes:
      - qbittorrent-config:/config:rw
      - qbittorrent-download:/downloads:rw
      - qbittorrent-watch:/watch:rw
    restart: unless-stopped

volumes:
  qbittorrent-config:
  qbittorrent-download:
  qbittorrent-watch:
