services:
  ## Mongo Express - MongoDB admin interface
  ## Docker Hub: https://hub.docker.com/_/mongo-express
  ## Docs:
  mongo-express:
    image: mongo-express:${MONGO_EXPRESS_VERSION:-latest}
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER:-mongo}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS:-insecurePass}
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USER:-mongo}:${MONGO_PASS:-insecurePass}@mongo:27017/"
      ME_CONFIG_BASICAUTH: false
    networks:
      - mongo-express

networks:
  mongo-express:
    name: mongo-express
