http:
  routers:
    pihole:
      entryPoints:
        - websecure
      rule: 'Host(`pihole.{{ DOMAIN }}`)'
      service: pihole
      middlewares:
        - pihole-redirectregex  # Apply the regex redirection middleware for Pi-hole

  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://{{ PIHOLE_URL }}"  # Define the backend server URL for Pi-hole

  middlewares:
    pihole-redirectregex:
      redirectRegex:
        regex: "^https?://pihole.{{ DOMAIN }}/$"  # Match the base Pi-hole URL
        replacement: "https://pihole.{{ DOMAIN }}/admin"  # Redirect to the Pi-hole admin page
