version: "3.7"

services:

  # FreshRSS - RSS Feed Aggregator
  #  https://hub.docker.com/r/freshrss/freshrss
  #
  freshrss:
    image: freshrss/freshrss:${FRESHRSS_VERSION:-latest}
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    networks:
      - proxy
      - postgres
    #ports:
    #  - "80:80"
    volumes:
      - "~/docker/freshrss/data:/var/www/FreshRSS/data"
      - "~/docker/freshrss/extensions:/var/www/FreshRSS/extensions"
    environment:
      - CRON_MIN=13,43
      - TZ=${FRESHRSS_TZ:-Europe/London}
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.freshrss-rtr.entrypoints=https"
      - "traefik.http.routers.freshrss-rtr.rule=Host(`rss.${DOMAIN}`)"
      - "traefik.http.routers.freshrss-rtr.tls=true"
      - "traefik.http.routers.freshrss-rtr.tls.certresolver=digitalocean"
      - "traefik.http.routers.freshrss-rtr.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.freshrss-rtr.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.routers.freshrss-rtr.tls.options=default"
      # HTTP Services
      - "traefik.http.routers.freshrss-rtr.service=freshrss-svc"
      - "traefik.http.services.freshrss-svc.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
  postgres:
    external: true
