version: "3.7"

services:

  # Nginx - Web Server
  # https://hub.docker.com/_/nginx
  #
  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    networks:
      - proxy
    #ports:
    #  - "8080:80"
    volumes:
      - "./html:/usr/share/nginx/html:ro"
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.nginx-rtr.entrypoints=https"
      - "traefik.http.routers.nginx-rtr.rule=Host(`web.${DOMAIN}`)"
      - "traefik.http.routers.nginx-rtr.tls=true"
      - "traefik.http.routers.nginx-rtr.tls.certresolver=digitalocean"
      - "traefik.http.routers.nginx-rtr.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.nginx-rtr.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.routers.nginx-rtr.tls.options=default"
      # HTTP Services
      - "traefik.http.routers.nginx-rtr.service=nginx-svc"
      - "traefik.http.services.nginx-svc.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
