version: "3.7"

services:

  # Gitea - Selfhosted Git Service
  #   https://docs.gitea.io/en-us/install-with-docker/
  #
  gitea:
    image: gitea/gitea:${GITEA_VERSION:-latest}
    container_name: gitea
    hostname: gitea
    restart: unless-stopped
    networks:
      - proxy
      - postgres
    #ports:
    #  - "3000:3000"
    #  - "2222:22"
    volumes:
      - "~/docker/gitea:/data"
    environment:
      - USER_UID=${UID:-1000}
      - USER_GID=${GID:-1000}
      - SSH_PORT=666
      - SSH_LISTEN_PORT=22
      - ROOT_URL=https://gitea.${DOMAIN}
      - DOMAIN=gitea.${DOMAIN}
      - SSH_DOMAIN=gitea.${DOMAIN}
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=${GITEA_DB_NAME:-gitea}
      - DB_USER=${GITEA_DB_USER:-gitea}
      - DB_PASSWD=${GITEA_DB_PASS:-password}
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__FROM=${GITEA__mailer__FROM}
      - GITEA__mailer__MAILER_TYPE=smtp
      - GITEA__mailer__HOST=${GITEA__mailer__HOST}
      - GITEA__mailer__IS_TLS_ENABLED=false
      - GITEA__mailer__USER=${GITEA__mailer__USER:-apikey}
      - GITEA__mailer__PASSWD="""${GITEA__mailer__PASSWD}"""
      - GITEA__mailer__SKIP_VERIFY=true
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.giteaWeb-rtr.entrypoints=https"
      - "traefik.http.routers.giteaWeb-rtr.rule=Host(`gitea.${DOMAIN}`)"
      - "traefik.http.routers.giteaWeb-rtr.tls=true"
      - "traefik.http.routers.giteaWeb-rtr.tls.certresolver=digitalocean"
      - "traefik.http.routers.giteaWeb-rtr.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.giteaWeb-rtr.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.routers.giteaWeb-rtr.tls.options=default"
      # HTTP Services
      - "traefik.http.routers.giteaWeb-rtr.service=giteaWeb-svc"
      - "traefik.http.services.giteaWeb-svc.loadbalancer.server.port=3000"
      # TCP
      - "traefik.tcp.routers.giteaSSH-rtr.entrypoints=ssh"
      - "traefik.tcp.routers.giteaSSH-rtr.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.giteaSSH-rtr.service=giteaSSH-svc"
      - "traefik.tcp.services.giteaSSH-svc.loadbalancer.server.port=22"

networks:
  proxy:
    external: true
  postgres:
    external: true
