version: "3.7"

services:

  db:
    image: postgres:${GITEA_DB_VERSION:-latest}
    container_name: gitea-db
    restart: unless-stopped
    networks:
      - gitea
    environment:
      - POSTGRES_DB=${GITEA_DB_NAME:-giteadb}
      - POSTGRES_USER=${GITEA_DB_USER:-gitea}
      - POSTGRES_PASSWORD=${GITEA_DB_PASS:-password}
    volumes:
      - ${DATA_PATH:-~/docker}/gitea/db:/var/lib/postgresql/data

  gitea:
    image: gitea/gitea:${GITEA_VERSION:-latest}
    container_name: gitea
    restart: unless-stopped
    networks:
      - gitea
    ports:
      - 3000:3000
      - 2222:22
    depends_on:
      - db
    volumes:
      - ${DATA_PATH:-~/docker}/gitea/data:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_PORT=22
      - SSH_LISTEN_PORT=22
      - ROOT_URL=http://gitea.${DOMAIN:-docker.localhost}
      - DOMAIN=gitea.${DOMAIN:-docker.localhost}
      - SSH_DOMAIN=gitea.${DOMAIN:-docker.localhost}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${GITEA_DB_NAME:-giteadb}
      - GITEA__database__USER=${GITEA_DB_USER:-gitea}
      - GITEA__database__PASSWD=${GITEA_DB_PASS:-password}

networks:
  gitea:
    name: gitea
