version: "3.7"

services:

  db:
    labels:
      - traefik.enable=false

  gitea:
    networks:
      - proxy
    environment:
      - SSH_PORT=666
      - ROOT_URL=http://gitea.${DOMAIN:-docker.localhost}
      - DOMAIN=gitea.${DOMAIN:-docker.localhost}
      - SSH_DOMAIN=gitea.${DOMAIN:-docker.localhost}
    labels:
      - traefik.enable=true
      # web
      - traefik.http.routers.giteaWeb-rtr.entrypoints=web
      - traefik.http.routers.giteaWeb-rtr.rule=Host(`gitea.${DOMAIN:-docker.localhost}`)
      - traefik.http.routers.giteaWeb-rtr.service=giteaWeb-svc
      - traefik.http.services.giteaWeb-svc.loadbalancer.server.port=3000
      # ssh
      - traefik.tcp.routers.giteaSSH-rtr.entrypoints=ssh
      - traefik.tcp.routers.giteaSSH-rtr.rule=HostSNI(`*`)
      - traefik.tcp.routers.giteaSSH-rtr.service=giteaSSH-svc
      - traefik.tcp.services.giteaSSH-svc.loadbalancer.server.port=22

networks:
  proxy:
    external: true
