version: "3.7"

services:

  db:
    image: postgres:14-alpine
    container_name: gitea-db
    restart: unless-stopped
    networks:
      - gitea
    environment:
      - POSTGRES_DB=${GITEA_DB_NAME:-giteadb}
      - POSTGRES_USER=${GITEA_DB_USER:-gitea}
      - POSTGRES_PASSWORD=${GITEA_DB_PASS:-password}
    volumes:
      - ${DATA_PATH:-gitea-db}:/var/lib/postgresql/data
    labels:
      - traefik.enable=false
    healthcheck:
      test: pg_isready -U ${GITEA_DB_USER:-gitea} -d ${GITEA_DB_NAME:-giteadb}
      interval: 10s
      timeout: 2s
      retries: 10

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    networks:
      - gitea
      - proxy
    # ports:
    #   - 3000:3000
    #   - 2222:22
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${DATA_PATH:-gitea-data}:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_PORT=666
      - SSH_LISTEN_PORT=22
      - ROOT_URL=http://gitea.${DOMAIN:-docker.localhost}
      - DOMAIN=gitea.${DOMAIN:-docker.localhost}
      - SSH_DOMAIN=gitea.${DOMAIN:-docker.localhost}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${GITEA_DB_NAME:-giteadb}
      - GITEA__database__USER=${GITEA_DB_USER:-gitea}
      - GITEA__database__PASSWD=${GITEA_DB_PASS:-password}
    labels:
      - traefik.enable=true
      # web
      - traefik.http.routers.giteaWeb-rtr.entrypoints=web
      - traefik.http.routers.giteaWeb-rtr.rule=Host(`gitea.${DOMAIN:-docker.localhost}`)
      - traefik.http.routers.giteaWeb-rtr.service=giteaWeb-svc
      - traefik.http.services.giteaWeb-svc.loadbalancer.server.port=3000
      # ssh
      - traefik.tcp.routers.giteaSSH-rtr.entrypoints=ssh
      - traefik.tcp.routers.giteaSSH-rtr.rule=HostSNI(`*`)
      - traefik.tcp.routers.giteaSSH-rtr.service=giteaSSH-svc
      - traefik.tcp.services.giteaSSH-svc.loadbalancer.server.port=22

networks:
  proxy:
    external: true
