services:

  traefik:
    ports:
      - 80:80
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.network=proxy
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --log.level=DEBUG
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-rtr.entrypoints=web
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.${DOMAIN:-docker.localhost}`)
      - traefik.http.routers.traefik-rtr.service=api@internal
