version: "3.7"

services:

  excalidraw:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.excalidraw-rtr.entrypoints=web
      - traefik.http.routers.excalidraw-rtr.rule=Host(`draw.${DOMAIN:-docker.localhost}`)
      - traefik.http.routers.excalidraw-rtr.service=excalidraw-svc
      - traefik.http.services.excalidraw-svc.loadbalancer.server.port=80

networks:
  proxy:
    external: true
