version: "3.7"

services:

  api:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.vikunjaAPI-rtr.entrypoints=web
      - traefik.http.routers.vikunjaAPI-rtr.rule=Host(`vikunja.${DOMAIN:-docker.localhost}`) && PathPrefix(`/api/v1`, `/dav/`, `/.well-known/`)

  frontend:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.vikunjaWeb-rtr.entrypoints=web
      - traefik.http.routers.vikunjaWeb-rtr.rule=Host(`vikunja.${DOMAIN:-docker.localhost}`)
      - traefik.http.routers.vikunjaWeb-rtr.service=vikunjaWeb-svc
      - traefik.http.services.vikunjaWeb-svc.loadbalancer.server.port=80

networks:
  proxy:
    external: true
