services:
  ## Portainer - Container Management
  ## Docker Hub: https://hub.docker.com/r/portainer/portainer-ce
  ## Docs: https://docs.portainer.io/
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION:-latest}
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9443:9443 # Self-signed SSL certificate secure port
    volumes:
      - portainer-data:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  portainer-data:
