services:
  ## Portainer - Container management
  ## Docker Hub:
  ## Docs:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION:-latest}
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - portainer-data:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  portainer-data:
