version: "3.7"

services:
  # Photoprism - Photo Management
  #   https://hub.docker.com/r/photoprism/photoprism
  #
  photoprism:
    image: photoprism/photoprism:${PHOTOPRISM_VERSION:-latest}
    container_name: photoprism
    hostname: photoprism
    restart: unless-stopped
    depends_on:
      - mariadb
    user: "${PHOTOPRISM_UID}:${PHOTOPRISM_GID}"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    networks:
      - proxy
      - mariadb
    #ports:
    #  - "2342:2342"
    #healthcheck:
    #  test: "photoprism status"
    #  interval: 60s
    #  timeout: 15s
    #  retries: 5
    volumes:
      - "~/docker/photoprism:/photoprism/storage"
      - "~/storage/photoprism/gallery:/photoprism/originals"
      - "~/storage/photoprism/import:/photoprism/import"
    environment:
      - PHOTOPRISM_DEBUG=false # Run in debug mode (shows additional log messages)
      - PHOTOPRISM_PUBLIC=false # No authentication required (disables password protection)
      - PHOTOPRISM_READONLY=false # Don't modify originals directory (reduced functionality)
      - PHOTOPRISM_UPLOAD_NSFW=true # Allow uploads that MAY be offensive
      - PHOTOPRISM_DETECT_NSFW=false # Flag photos as private that MAY be offensive (requires TensorFlow)
      - PHOTOPRISM_EXPERIMENTAL=false # Enables experimental features
      - PHOTOPRISM_DISABLE_SETTINGS=false # Disables Settings in Web UI
      #- PHOTOPRISM_DATABASE_DRIVER=sqlite
      - PHOTOPRISM_DATABASE_DRIVER=mysql # Use MariaDB (or MySQL) instead of SQLite for improved performance
      - PHOTOPRISM_DATABASE_SERVER=mariadb:3306 # MariaDB database server (hostname:port)
      - PHOTOPRISM_DATABASE_NAME=${MYSQL_DATABASE:-photoprism} # MariaDB database schema name
      - PHOTOPRISM_DATABASE_USER=${MYSQL_USER:-photoprism} # MariaDB database user name
      - PHOTOPRISM_DATABASE_PASSWORD=${MYSQL_PASSWORD:-password} # MariaDB database user password
      - PHOTOPRISM_ADMIN_PASSWORD=${PHOTOPRISM_PASSWORD:-photoprism}
      - PHOTOPRISM_SITE_URL=https://photos.${DOMAIN}/
      - PHOTOPRISM_SITE_TITLE=PhotoPrism
      - PHOTOPRISM_SITE_CAPTION=
      - PHOTOPRISM_SITE_DESCRIPTION=
      - PHOTOPRISM_SITE_AUTHOR=
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.photoprism-rtr.entrypoints=https"
      - "traefik.http.routers.photoprism-rtr.rule=Host(`photos.${DOMAIN}`)"
      - "traefik.http.routers.photoprism-rtr.tls=true"
      - "traefik.http.routers.photoprism-rtr.tls.certresolver=digitalocean"
      - "traefik.http.routers.photoprism-rtr.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.photoprism-rtr.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.routers.photoprism-rtr.tls.options=default"
      # HTTP Services
      - "traefik.http.routers.photoprism-rtr.service=photoprism-svc"
      - "traefik.http.services.photoprism-svc.loadbalancer.server.port=2342"

  # Mariadb - Photo Management
  #   https://hub.docker.com/_/mariadb
  #
  mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    networks:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes:
      - "~/docker/photoprism/mariadb:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-photoprism}
      - MYSQL_USER=${MYSQL_USER:-photoprism}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}

networks:
  proxy:
    external: true
  mariadb:
    external: true
