version: "3.7"

services:

  db:
    image: postgres:12-alpine
    container_name: nocodb-db
    restart: unless-stopped
    networks:
      - nocodb
    volumes:
      - ${NC_PATH:-nocodb-db}:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=${NC_DB_NAME:-nocodb}
      - POSTGRES_USER=${NC_DB_USER:-nocodb}
      - POSTGRES_PASSWORD=${NC_DB_PASS:-password}
    healthcheck:
      test: pg_isready -U ${NC_DB_USER:-nocodb} -d ${NC_DB_NAME:-nocodb}
      interval: 10s
      timeout: 2s
      retries: 10

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nocodb
    volumes:
      - ${NC_PATH:-nocodb-data}:/usr/app/data:rw
    environment:
      - NC_DB=pg://db:5432?u=${NC_DB_USER:-nocodb}&p=${NC_DB_PASS:-password}&d=${NC_DB_NAME:-nocodb}
      - NC_DISABLE_TELE=true

volumes:
  nocodb-db:
    name: nocodb-db
  nocodb-data:
    name: nocodb-data

networks:
  nocodb:
    name: nocodb
