version: "3.7"

services:

  # Postgres – Database Server
  #   https://hub.docker.com/_/postgres
  #
  # docker exec -it postgres psql -U ${POSTGRES_USER}
  #
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    networks:
      - postgres
    #ports:
    #  - "5432:5432"
    environment:
      - TZ=${POSTGRES_TZ}
      - PGTZ=${POSTGRES_TZ}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASS:-password}
    volumes:
      - "~/docker/shared/db:/docker-entrypoint-initdb.d" # Create databases at first boot
      - "~/docker/postgres:/var/lib/postgresql/data"
    labels:
      - traefik.enable=false

networks:
  postgres:
    external: true
