version: "3.7"

services:

  # MongoDB - Document Database
  #   https://hub.docker.com/_/mongo/
  #
  mongo:
    image: mongo:${MONGO_VERSION:-latest}
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    networks:
      - mongo
    #ports:
    #  - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-mongo}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS:-password}
    volumes:
      - "~/docker/mongo:/data/db"
    labels:
      - traefik.enable=false

networks:
  mongo:
    external: true
